version: '3'

services:
  postgres:
      image: postgres:14.5-alpine3.16
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`s1mple133-vmhtl.ddns.net`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: postgres
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_HOSTNAME_STRICT: "false"
        KC_HTTP_ENABLED: "true"
        KC_HTTP_PORT: 80
        KC_FEATURES:
          authorization
          token-exchange
          docker
          impersonation
          scripts
          upload-scripts
          web-authn
          client-policies
          dynamic-scopes
      entrypoint: /opt/keycloak/bin/kc.sh start
      depends_on:
        - postgres
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=pavelescu_darius@yahoo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"