version: '3'

services:
  postgres:
      image: postgres:15.2-alpine
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  keycloak:
      image: quay.io/keycloak/keycloak:20.0.3
      ports:
        - 8081:8081
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: postgres
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_HOSTNAME_STRICT: "false"
        KC_HTTP_ENABLED: "true"
        KC_HTTP_PORT: 8081
        KC_FEATURES:
          authorization
          token-exchange
          docker
          impersonation
          scripts
          upload-scripts
          web-authn
          client-policies
          dynamic-scopes
      entrypoint: /opt/keycloak/bin/kc.sh start
      depends_on:
        - postgres
